# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('phone_no', models.CharField(default=None, max_length=20)),
                ('group_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('maker', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alpha_users',
            },
        ),
    ]
