# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
                ('maker', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alpha_user_groups',
            },
        ),
    ]
